language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install --use-wheel --upgrade --cache-dir .cache/pip Pygments setuptools docutils mock pillow alabaster commonmark recommonmark mkdocs
script:
  - mkdocs build --clean --site-dir _build/html --theme readthedocs

matrix:
  include:
  ## linters for json and JavaScript files
    - language: node_js
      node_js:
        - 8
      python:
      install:
        - npm install -g markdownlint-cli --save-dev
      before_script:
        - markdownlint .
      script:
        - true  # add other tests here

notifications:
  on_success: change
  on_failure: always
