language: nodejs
node_js:
  - 8
install:
  - npm install -g markdownlint-cli --save-dev
before_script:
  - markdownlint .
script:
  - true  # add other tests here

notifications:
  on_success: change
  on_failure: always
