site_name: Guidelines to Join FIWARE Lab
repo_url: https://github.com/martel-innovate/join-fiware-lab-guide.git
edit_uri: edit/master/docs
site_description: The official guidelines to connect an OpenStack cloud to FIWARE Lab
docs_dir: 'docs'
theme: readthedocs
pages:
    - Home: 'index.md'
    - 'Essential things to know before joining FIWARE Lab':
      - 'Introduction': '1.essentials/1.introduction.md'
      - 'Requirements': '1.essentials/2.requirements.md'
      - 'Steps to become a New FIWARE Lab node': '1.essentials/3.steps_join.md'
      - 'Steps to discontinue a FIWARE Lab node': '1.essentials/4.steps_leave.md'
      - 'Steps to show the current status of your FIWARE Lab node': '1.essentials/5.steps_status.md'
    - 'Policies':
      - 'Privacy Policy': '2.policies/1.privacy.md'
      - 'Cookies policy': '2.policies/2.cookies.md'
      - 'Terms & Conditions': '2.policies/3.terms.md'

markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
