site_name: Guidelines to Join FIWARE Lab
repo_url: https://github.com/martel-innovate/join-fiware-lab-guide.git
edit_uri: edit/master/docs
site_description: The official guidelines to connect an OpenStack cloud to FIWARE Lab
docs_dir: 'docs'
theme: readthedocs
pages:
    - Home: 'index.md'
    - 'Essential things to know before joining FIWARE Lab':
      - 'Introduction': '1.essentials/1.introduction.md'
      - 'Requirements': '1.essentials/2.requirements.md'
      - 'Steps to become a New FIWARE Lab node': '1.essentials/3.steps_join.md'
      - 'Steps to discontinue a FIWARE Lab node': '1.essentials/4.steps_leave.md'
      - 'Steps to show the current status of your FIWARE Lab node': '1.essentials/5.steps_status.md'
    - 'Policies':
      - 'Privacy Policy': '2.policies/1.privacy.md'
      - 'Cookies policy': '2.policies/2.cookies.md'
      - 'Terms & Conditions': '2.policies/3.terms.md'
    - 'Process for joining FIWARE Lab':
      - 'OpenStack Services Required': '3.process/1.services.md'
      - 'OpenStack upgrade version policy in FIWARE Lab': '3.process/2.upgrade.md'
      - 'Installing FIWARE Lab Node': '3.process/3.installing.md'
      - 'Configuring FIWARE Lab Node': '3.process/4.configuring.md'
      - 'Check the Status of OpenStack services': '3.process/5.statuscheck.md'
      - 'Testing FIWARE Lab Node locally': '3.process/6.testing.md'
      - 'Connecting your Node to FIWARE Lab': '3.process/7.connecting.md'
      - 'Registering your Node in FI-Health': '3.process/8.fi-health.md'
      - 'Registering your Node in the Infographics': '3.process/9.infographics.md'
      - 'Registering your Node in Deep Log Inspection': '3.process/10.log.md'
    - 'Operating and Maintaining a FIWARE Lab node':
      - 'Introduction': '4.operation/1.introduction.md'
      - 'Deep Log Inspection': '4.operation/2.deep-log.md'
      - 'FI-Health': '4.operation/3.fi-health.md'
      - 'Rancher': '4.operation/5.rancher.md'
      - 'Mastermind': '4.operation/6.mastermind.md'
      - 'JIRA': '4.operation/7.jira.md'
      - 'Backlog': '4.operation/8.backlog.md'
    - 'Management operations on a FIWARE Lab node':
      - 'Account Management': '5.management/1.account.md'
      - 'Base-images Management': '5.management/2.base-image.md'
    - 'Overview of FIWARE Lab node coordination and support':
      - 'Introduction': '6.coordination/1.introduction.md'
      - 'Coordination and support procedures': '6.coordination/2.procedures.md'
      - 'FIWARE Lab Statistics': '6.coordination/3.statistics.md'


markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
